### ISSUE TITLE
User Database Object (1SP)

### ISSUE THREAD

**Issue by skittlebearz** [skittlebearz/7thLevelPutPut#23]
Keep track of wallet and score card

**Comment by jonscoresby** [comment]
https://github.com/skittlebearz/7thLevelPutPut/pull/35

**Comment by jonscoresby** [comment]
I used the following tutorial to extend the user object included with django:
https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#onetoone
